-- Bills table
-- Stores bills belonging to each user.

CREATE TABLE public.bills (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id uuid NOT NULL,
    bill_name text NOT NULL,
    amount numeric(10, 2) NOT NULL,
    due_date date NOT NULL,
    paid boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT now(),

    CONSTRAINT bills_pkey PRIMARY KEY (id),

    CONSTRAINT bills_user_id_bill_name_key
        UNIQUE (user_id, bill_name),

    CONSTRAINT bills_user_id_fkey
        FOREIGN KEY (user_id)
        REFERENCES profiles (id)
        ON DELETE CASCADE,

    CONSTRAINT bills_amount_check
        CHECK (amount > 0)
);