-- Budgets table
-- Stores each user's monthly budget.

CREATE TABLE public.budgets (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id uuid NOT NULL,
    budget_month date NOT NULL,
    amount numeric(12, 2) NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),

    CONSTRAINT budgets_pkey
        PRIMARY KEY (id),

    CONSTRAINT budgets_user_month_unique
        UNIQUE (user_id, budget_month),

    CONSTRAINT budgets_user_id_fkey
        FOREIGN KEY (user_id)
        REFERENCES profiles (id)
        ON DELETE CASCADE,

    CONSTRAINT budgets_amount_check
        CHECK (amount > 0),

    CONSTRAINT budgets_month_first_day
        CHECK (EXTRACT(day FROM budget_month) = 1)
);