-- ============================================================
-- Profiles Table
-- Stores application-specific user information.
--
-- Supabase Authentication stores login-related information
-- such as email, password hash, and session data.
--
-- This table stores profile information used by the
-- Expense Tracker application.
-- ============================================================


-- Create the profiles table if it does not already exist.
CREATE TABLE IF NOT EXISTS public.profiles (
    -- Use the same UUID generated by Supabase Authentication.
    -- This column is both:
    -- 1. The primary key of the profiles table.
    -- 2. A foreign key referencing auth.users.
    id UUID PRIMARY KEY
        REFERENCES auth.users(id)
        ON DELETE CASCADE,

    -- Store the user's full name.
    full_name TEXT NOT NULL
);


-- Enable Row Level Security so database policies can control
-- which profile rows authenticated users may access.
ALTER TABLE public.profiles
ENABLE ROW LEVEL SECURITY;


-- Allow authenticated users to create only their own profile.
-- The profile ID must match the logged-in user's UUID.
CREATE POLICY "Users can insert their own profile"
ON public.profiles
FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = id);


-- Allow authenticated users to view only their own profile.
CREATE POLICY "Users can view their own profile"
ON public.profiles
FOR SELECT
TO authenticated
USING (auth.uid() = id);


-- ============================================================
-- Automatic Profile Creation
--
-- This function runs after Supabase creates a new authentication
-- user. It copies the user's UUID and full name into profiles.
-- ============================================================

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
    INSERT INTO public.profiles (id, full_name)
    VALUES (
        NEW.id,
        NEW.raw_user_meta_data ->> 'full_name'
    );

    RETURN NEW;
END;
$$;


-- Run handle_new_user() automatically whenever a new row is
-- inserted into Supabase's auth.users table.
CREATE TRIGGER on_auth_user_created
AFTER INSERT ON auth.users
FOR EACH ROW
EXECUTE FUNCTION public.handle_new_user();